# supervaize_hello_world/tests/conftest.py
"""Shared fixtures for hello-world E2E tests."""
import pytest
from fastapi.testclient import TestClient

import agent_data_resource as _dr_module


@pytest.fixture(autouse=True)
def reset_contacts():
    """Reset in-memory contacts store before each test."""
    _dr_module._contacts.clear()
    _dr_module._contacts.update({
        "c1": {"id": "c1", "first_name": "Alice", "last_name": "Smith", "email": "alice@example.com", "city": "Paris"},
        "c2": {"id": "c2", "first_name": "Bob", "last_name": "Jones", "email": "bob@example.com", "city": "London"},
    })


@pytest.fixture(scope="session")
def api_key():
    """The server API key — auto-generated by the SDK at startup."""
    from supervaizer_control import sv_server
    return sv_server.api_key


@pytest.fixture(scope="session")
def client(api_key):
    """FastAPI TestClient authenticated with the server API key."""
    from supervaizer_control import sv_server
    with TestClient(sv_server.app) as c:
        c.headers.update({"X-API-Key": api_key})
        yield c
